### ISSUE TITLE
GitLab CI Support

### ISSUE THREAD

**Issue by AstraLuma** [cirruslabs/cirrus-cli#125]
Add support for running GitLab CI jobs.

**Comment by fkorotkov** [comment]
Did you mean running Cirrus tasks in GitLab? Or actually read '.gitlab-CI.yml' and run jobs from there?

**Comment by AstraLuma** [comment]
read `.gitlab-ci.yml` and run them locally.

**Comment by fkorotkov** [comment]
This is out of scope for this project. It seems [GitLab runner was able to run jobs locally](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/312) at some point but they deprecated it. 😪 But anyways we should add documentation on how to run Cirrus CLI in GitLab.

**Comment by AstraLuma** [comment]
Yeah, that ability never worked very well. When I looked into it, there was a silly amount of caveats.

Why is this out of scope? Your goal is to run various CI pipelines locally, and support 5 other 3rd party CI tools.

**Comment by AstraLuma** [comment]
oh nvm, i should read that more closely.
