### ISSUE TITLE
Run "clone" in a separate container

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#13]
Let's run CLI's clone instruction in a separate container (for example, `alpine:latest`) since the task container might not have `cp` or `rsync` on the $PATH.

For example [Kaniko](https://github.com/GoogleContainerTools/kaniko) executor image `gcr.io/kaniko-project/executor` doesn't have anything.

**Comment by edigaryev** [comment]
This was implemented as a part of https://github.com/cirruslabs/cirrus-cli/pull/22 and the clone instruction is now being run in the container based on the [cirrus-ci-agent](https://github.com/cirruslabs/cirrus-ci-agent)'s image, which is in turn based on `alpine:latest`.
