### ISSUE TITLE
Use rsync to speed up "clone"

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#14]
Right now `cp` can take a lot of time. For example, it took almost 3 minutes to execute it for https://github.com/cirruslabs/cirrus-ci-web when I had `node_modules` locally.

One option will be to use `rsync` if repository has `.gitignore` availabe. It seems [rsync can respect `.gitignore`](https://stackoverflow.com/a/15373763) which shoiuld significantly speed up "`clone`" time.

This issue can be cooped with #13 in order to make sure `rsync` is available inside a container we control.

**Comment by edigaryev** [comment]
This was implemented as a part of https://github.com/cirruslabs/cirrus-cli/pull/22.
