### ISSUE TITLE
Option for non-emoji output

### ISSUE THREAD

**Issue by duckinator** [cirruslabs/cirrus-cli#150]
In some cases my terminals aren't set up for emoji support, so it'd be nice to have a way (maybe an environment variable?) to disable emoji.

One way to do this is instead of ✅ and ❌ you could go with `[OKAY]` and `[FAIL]`. I'm not sure what would make the most sense to replace the clocks, but one possibility could be something like cycling through these:

```
[-   ]
[ -  ]
[  - ]
[   -]
[  - ]
[ -  ]
```

I've encountered this problem when using urxvt with certain fonts and when using the local console directly (as opposed to a terminal emulator in Xorg/Wayland) on Manjaro Linux.

(EDIT: Changed wording because the problem is specifically emoji.)

**Comment by fkorotkov** [comment]
Will something like we have for Windows which also doesn't have Emojis by default work for you?

![cli-windows](https://user-images.githubusercontent.com/989066/98590111-4d2d7780-229c-11eb-95c8-64a0e79d169d.gif)

**Comment by duckinator** [comment]
Yes, that would work fine!
