### ISSUE TITLE
Config was parsed correctly but no tasks were found!

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-cli#174]
https://github.com/AlexWayfer/flame-cli/pull/57

Probably because of https://github.com/cirruslabs/cirrus-ci-docs/issues/689

**Comment by edigaryev** [comment]
Please take a look at the CLI's version [0.19.0](https://github.com/cirruslabs/cirrus-cli/releases/tag/v0.19.0) that was just released, it should support `.cirrus.yaml` now.

**Comment by AlexWayfer** [comment]
Sorry, but I can't confirm:

```
> sudo cirrus --version
cirrus version 0.20.1-unknown

> sudo cirrus run
2020/12/03 01:31:01 Config was parsed correctly but no tasks were found!
Error: run failed
2020/12/03 01:31:01 run failed

> ls -lah .cirrus.yaml
-rw-r--r-- 1 alex alex 3.1K Dec  3 01:28 .cirrus.yaml
```

**Comment by edigaryev** [comment]
> Sorry, but I can't confirm:
> 
> ```
> > sudo cirrus --version
> cirrus version 0.20.1-unknown
> 
> > sudo cirrus run
> 2020/12/03 01:31:01 Config was parsed correctly but no tasks were found!
> Error: run failed
> 2020/12/03 01:31:01 run failed
> 
> > ls -lah .cirrus.yaml
> -rw-r--r-- 1 alex alex 3.1K Dec  3 01:28 .cirrus.yaml
> ```

Looks like you have [some `only_if` conditions](https://github.com/AlexWayfer/flame-cli/blob/e49dc0cb4fb93b2ec6ad884080ca9c175a4bece6/.cirrus.yaml#L24-L27) in your `.cirrus.yaml` that don't get evaluated to `true`. This results in parser skipping those tasks.

You can try supplying the missing environment variables to make this work:

```
cirrus run -e CIRRUS_BRANCH=master
```

**Comment by AlexWayfer** [comment]
> > Sorry, but I can't confirm:
> > ```
> > > sudo cirrus --version
> > cirrus version 0.20.1-unknown
> > 
> > > sudo cirrus run
> > 2020/12/03 01:31:01 Config was parsed correctly but no tasks were found!
> > Error: run failed
> > 2020/12/03 01:31:01 run failed
> > 
> > > ls -lah .cirrus.yaml
> > -rw-r--r-- 1 alex alex 3.1K Dec  3 01:28 .cirrus.yaml
> > ```
> 
> Looks like you have [some `only_if` conditions](https://github.com/AlexWayfer/flame-cli/blob/e49dc0cb4fb93b2ec6ad884080ca9c175a4bece6/.cirrus.yaml#L24-L27) in your `.cirrus.yaml` that don't get evaluated to `true`. This results in parser skipping those tasks.
> 
> You can try supplying the missing environment variables to make this work:
> 
> ```
> cirrus run -e CIRRUS_BRANCH=master
> ```

OK, thank you! Sorry, forgot about this.
