### ISSUE TITLE
Stream launched container's logs to the CLI's logger

### ISSUE THREAD

**Issue by edigaryev** [cirruslabs/cirrus-cli#187]
This is helpful for the root cause diagnosis, especially when implementing new functionality.

There will be a quite amount of logs, but doing this with the trace level should probably be OK from the UX standpoint.

**Comment by fkorotkov** [comment]
What kind of logs you mean? Stdout and stderr of the containers which will contain agents output in case of the error?

**Comment by edigaryev** [comment]
> What kind of logs you mean? Stdout and stderr of the containers which will contain agents output in case of the error?

Yes, exactly.

**Comment by fkorotkov** [comment]
Got it. Yeah, maybe add it with debug level. 🤔
