### ISSUE TITLE
Include injected files in docker image hash

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#222]
Once we move the cloud to the Go parser we should add tracking of files `ADD`ed or `COPY`ed in `Dockerfile`s. See https://github.com/cirruslabs/cirrus-ci-docs/issues/273 for details.

**Comment by fkorotkov** [comment]
We can add the following hashes to `CirrusConfigurationEvaluatorService#EvaluateConfig` response:

```proto
message DockerfileFingerprint {
  string fingerprint = 1;
  string path = 2;
  map<string, string> arguments = 3;
  bool precise = 4; // false when folders were injected via COPY/ADD
}
```

For backward compatibility if a Dockerfile's fingerprint can't be precisly calculated we can set the `precise` flag and add a warning on the task and fall back to the current behaviour.

**Comment by fkorotkov** [comment]
Or instead of a boolean flag return a list of issues similar to the parsing one.

**Comment by edigaryev** [comment]
Duplicate of https://github.com/cirruslabs/cirrus-cli/issues/447, which was closed today by https://github.com/cirruslabs/cirrus-cli/pull/452.
