### ISSUE TITLE
Switch to Go parser by default

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#251]
I think it's time to switch to Go parser by default instead of the RPC one. The Go parser is almost there are is working perfectly in most of the cases. IMO we can switch the default parser for the CLI while still polishing last corner cases of compatibility with the cloud parser.

**Comment by edigaryev** [comment]
Temporarily reverted in https://github.com/cirruslabs/cirrus-cli/pull/258.
