### ISSUE TITLE
--debug-no-cleanup doesn't seem working

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#292]
I'm running the following command for the [docs](https://github.com/cirruslabs/cirrus-ci-docs) repo and don't see any containers left after the execution.

```console
❯ cirrus run --debug-no-cleanup "Spell Check"
✅ 'Spell Check' Task 13s

❯ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

❯ cirrus --version 
cirrus version 0.34.0-c95096d
```

**Comment by edigaryev** [comment]
The container is there, it's just exited after successfully completing the task.

Try `docker ps -a` instead.

**Comment by fkorotkov** [comment]
What we can do so it's easier to run a shell inside such containers after task execution? This is the main use case for `--debug-no-cleanup`: shell into the container to inspect files and processes.

**Comment by edigaryev** [comment]
> What we can do so it's easier to run a shell inside such containers after task execution? This is the main use case for `--debug-no-cleanup`: shell into the container to inspect files and processes.

One option is to simply insert the following instruction into the task:

```
always:
  pause_script: sleep 3600
```

The other is to print the help command at the end of the execution. The command will run the exact container used for build if `--debug-no-cleanup` was specified and the container has exited, something like this:

```
The container has terminated, but you can shell into it by running it again:

$ docker run -it <container ID>
```

**Comment by fkorotkov** [comment]
I don't think `docker run` will work since it expects an image. We'll need to commit it first. And then there is a problem of changes outside of the volume that we mounted. Seems they will be lost. `sleep` might be an option with an echo like "Keeping container live for debug purposes..." 🤔

**Comment by edigaryev** [comment]
> `sleep` might be an option with an echo like "Keeping container live for debug purposes..." 🤔

Maybe, but I wonder what's your use-case for this anyway?

**Comment by fkorotkov** [comment]
For example, I was playing around with [Qodana](https://github.com/cirruslabs/cirrus-ci-annotations/issues/25) the other night and had issues figuring out where Qodana puts reports. I was specifying a folder but it was empty so I wanted to inspect the container to look around for the reports.
