### ISSUE TITLE
Option to override default registry

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#30]
Right now [Docker as a CI environment](https://cirrus-ci.org/guide/docker-builder-vm/#dockerfile-as-a-ci-environment) always uses `gcr.io` as registry. For local runs with CLI it might be usefully to override it. Consider the following use case: CLI is used in a private on-premise Jenkins cluster where there is a local Docker registry under `hub.mycorp.internal`. It will be great to override `gcr.io` with `hub.mycorp.internal` as well as allow to push a newly built `PrebuiltImage` to the registry directly from the CLI.

**Comment by fkorotkov** [comment]
Maybe something like `--prebuilt-image-template=ghcr.io/cirruslabs/prebuilt-cache:%s` flag to define where image is stored based on the Dockerfile hash `%s`. Right now it's `gcr.io/cirrus-ci-community/%s:latest`. And another flag like `--prebuilt-image-push` to attempt to push the image on misses (this will require Docker being authenticated with the registry).

**Comment by edigaryev** [comment]
> Maybe something like `--prebuilt-image-template=ghcr.io/cirruslabs/prebuilt-cache:%s` flag to define where image is stored based on the Dockerfile hash `%s`. Right now it's `gcr.io/cirrus-ci-community/%s:latest`. And another flag like `--prebuilt-image-push` to attempt to push the image on misses (this will require Docker being authenticated with the registry).

What do you think about reusing the [`registry_config`](https://cirrus-ci.org/guide/linux/?h=+registry#working-with-private-registries) configuration option instead, and extending the YAML configuration by adding the image template field to the `container`-like instances from the future-proofing perspective?

**Comment by fkorotkov** [comment]
Or maybe even reuse `image` field?

```yaml
task:
  container:
    image: ghcr.io/cirruslabs/prebuilt-cache:%s # template where dockerfile's hash will be passed
    dockerfile: .ci/Dockerfile
    registry_config: ENCRYPTED[...]
```

What do you think?

**Comment by edigaryev** [comment]
> Or maybe even reuse `image` field?
> 
> ```yaml
> task:
>   container:
>     image: ghcr.io/cirruslabs/prebuilt-cache:%s # template where dockerfile's hash will be passed
>     dockerfile: .ci/Dockerfile
>     registry_config: ENCRYPTED[...]
> ```
> 
> What do you think?

Looks dope and it seems that `%s can be used unambiguously in a [repository tag](https://docs.docker.com/engine/reference/commandline/tag/#extended-description):

>A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.

As for the `--prebuilt-image-push`: we can always try to push and fail gracefully.

Or there are cases where this is not desirable? If yes, then can provide a flag similar to `--container-no-pull` and name it `--container-no-push` for easier understanding, however, I'm not sure about how it'll be controlled in the cloud, though, if that feature is really needed.

**Comment by fkorotkov** [comment]
With pushing we need to focus on a use case of running a simple task: in that case the template references our gcr.io registry under cirrus-ci-community project. So IMO pushing should be disabled by default and allow users to opt-in.
