### ISSUE TITLE
Lint Cirrus Config

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#321]
We should probably start linting config files at some point. For example, report unknown YAML node names. For example, when users use `task_foo` syntax instead of `foo_task`, report that  `task_foo` is not valid.

Just opening the issue to track the issue and collect ideas about what can be linted.

**Comment by edigaryev** [comment]
How is linting different from e.g. `cirrus validate`?

**Comment by fkorotkov** [comment]
There is no error on `task_foo`. We can just throw an error too probably. 🤔

**Comment by fkorotkov** [comment]
Closing in favor of https://github.com/cirruslabs/cirrus-cli/issues/329
