### ISSUE TITLE
Ignore `depends_on` for `run` specific task

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-cli#342]
Hello.

I have such `.cirrus.yaml`: https://github.com/filewatcher/filewatcher-cli/blob/1f7a67b/.cirrus.yaml

Shortly, there are `remark` and `rubocop` tasks without `depends_on`, they're running correctly, and `test` task, which `depends_on` both of them.

And I want to run exactly `test` task, but I see empty output and even status 0:

```
> sudo cirrus run test -e CIRRUS_BRANCH=master -o simple --verbose
gRPC server is listening at unix:///tmp/cli-adc09646-11a0-4a17-b070-291f0298d215/cli.sock (unix:/tmp/cli-adc09646-11a0-4a17-b070-291f0298d215/cli.sock inside of a container)

> echo $status
0
```

(Also I'd like to run this task only with specific container from matrix, but I think it should be separate issue)

**Comment by edigaryev** [comment]
>And I want to run exactly `test` task, but I see empty output and even status 0:

Since you've redefined your task's name with `name: Test on $CIRRUS_OS`, you need to use the following name instead:

```
cirrus run "Test on Linux" -e CIRRUS_BRANCH=master -o simple --verbose
```

>Also I'd like to run this task only with specific container from matrix, but I think it should be separate issue

This is [possible too](https://github.com/cirruslabs/cirrus-cli/issues/63):

```
cirrus run "Test on Linux container:jruby:latest" -e CIRRUS_BRANCH=master -o simple --verbose
```

I've also added the error in #343 to make it more evident when no tasks match.

**Comment by AlexWayfer** [comment]
Thank you very much! ❤️ I forgot about renamed task. 🙈
