### ISSUE TITLE
Persistent worker: remove working directory cleaner

### ISSUE THREAD

**Issue by edigaryev** [cirruslabs/cirrus-cli#357]
Added in #356.

Also see https://github.com/cirruslabs/cirrus-cli/issues/352#issuecomment-811976981.

**Comment by MarcoFalke** [comment]
I just tried v0.45.0-07fb74e, but it didn't clear the directory. I presume the cirrus agent needs to be bumped on the cirrus servers first?

**Comment by edigaryev** [comment]
> I just tried v0.45.0-07fb74e, but it didn't clear the directory. I presume the cirrus agent needs to be bumped on the cirrus servers first?

I'm sorry you've had to test this by yourself, there was a logic error in the agent that should be fixed as a part of [0.45.1 CLI's release](https://github.com/cirruslabs/cirrus-cli/releases/tag/v0.45.1) (which itself will point to the latest agent release with the fix), binaries for which will be available shortly 🙌

**Comment by MarcoFalke** [comment]
No worries, thanks for working on this. I just re-tested and it looks like it prefers the directory name `/tmp/cirrus-build-557367079/` over `/tmp/cirrus-ci-build/`

**Comment by edigaryev** [comment]
> No worries, thanks for working on this. I just re-tested and it looks like it prefers the directory name `/tmp/cirrus-build-557367079/` over `/tmp/cirrus-ci-build/`

Thanks, this means it's working. These should also be removed automatically after the task completes.

This issue is just a TODO to remove the logic in https://github.com/cirruslabs/cirrus-cli/pull/356/commits/6004e6fdbf9c4f0d0e456004bc901329f149a078 after some time in the future.

**Comment by MarcoFalke** [comment]
Oh, I wanted to say that if a random directory name is picked (which may be included in cache artefacts), then it will be harder to re-use a cache between runs. We might be able to strip the path name from the cache, but if it is easy to always pick the `/tmp/cirrus-ci-build/` folder, then we'll probably prefer that.

**Comment by edigaryev** [comment]
> Oh, I wanted to say that if a random directory name is picked (which may be included in cache artefacts), then it will be harder to re-use a cache between runs. We might be able to strip the path name from the cache, but if it is easy to always pick the `/tmp/cirrus-ci-build/` folder, then we'll probably prefer that.

As far as I am aware this shouldn't be a problem since agent creates cache archives with relative paths, see https://github.com/cirruslabs/cirrus-ci-agent/blob/8996f9a23116c73960944eb6e6ae5bb33137592a/internal/targz/targz.go#L52.

Or you're talking about different caching mechanism?

**Comment by MarcoFalke** [comment]
> agent creates cache archives with relative paths

Ah, I see.

> Or you're talking about different caching mechanism?

The caches itself might include the full path. E.g. ccache. But this can be worked around for most compiler caches.

**Comment by edigaryev** [comment]
> The caches itself might include the full path. E.g. ccache. But this can be worked around for most compiler caches.

A fix for this was shipped in the [0.46.0 CLI's release](https://github.com/cirruslabs/cirrus-cli/releases/tag/v0.46.0).

**Comment by MarcoFalke** [comment]
Cool, thanks! I'll try this out in the next days.
