### ISSUE TITLE
Can't run Windows tasks

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-cli#364]
Hello.

I see you have implemented Windows support in CLI, and found no issues about it, but I have one:

```
> sudo cirrus run "Test on Windows" -e CIRRUS_BRANCH=master -o simple
[sudo] password for alex: 
Started 'Test on windows' Task
Started 'Preparing execution environment...'
Preparing volume to work with...
Failed to create a volume from working directory: working volume creation failed: when creating helper container: Error response from daemon: invalid mount config for type "volume": invalid mount path: 'C:/agent-volume' mount path must be absolute
'Preparing execution environment...' failed in 1.4s!
Error: working volume creation failed: when creating helper container: Error response from daemon: invalid mount config for type "volume": invalid mount path: 'C:/agent-volume' mount path must be absolute
2021/04/12 23:48:23 working volume creation failed: when creating helper container: Error response from daemon: invalid mount config for type "volume": invalid mount path: 'C:/agent-volume' mount path must be absolute
```

Working on this project (PR): https://github.com/filewatcher/filewatcher/pull/177

Arch Linux.

**Comment by edigaryev** [comment]
Hello!

Windows Containers are indeed supported, but you need to run the CLI directly on the Windows platform.

**Comment by AlexWayfer** [comment]
> Windows Containers are indeed supported, but you need to run the CLI directly on the Windows platform.

Oh! Oh… as I remember it's a Docker thing, I forgot about this… OK,  thank you, sorry to bother.

**Comment by AlexWayfer** [comment]
The same on Windows in Virtual Machine (via GNOME Boxes, it uses QEMU).

**Comment by AlexWayfer** [comment]
> > The same on Windows in Virtual Machine (via GNOME Boxes, it uses QEMU).
> 
> Are you running Docker Desktop or Windows Server with [Windows Containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/about/)?

Docker Desktop.

**Comment by edigaryev** [comment]
> > > The same on Windows in Virtual Machine (via GNOME Boxes, it uses QEMU).
> > 
> > 
> > Are you running Docker Desktop or Windows Server with [Windows Containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/about/)?
> 
> Docker Desktop.

Assuming you're running containers for Windows platform, have you tried [switching to Windows containers](https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers)? As far as I'm aware Docker Desktop runs Linux containers by default.

Afterwards, does something like`docker run -it --rm cirrusci/windowsservercore:2019` work?

**Comment by AlexWayfer** [comment]
> > > > The same on Windows in Virtual Machine (via GNOME Boxes, it uses QEMU).
> > > 
> > > 
> > > Are you running Docker Desktop or Windows Server with [Windows Containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/about/)?
> > 
> > 
> > Docker Desktop.
> 
> Assuming you're running containers for Windows platform, have you tried [switching to Windows containers](https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers)? As far as I'm aware Docker Desktop runs Linux containers by default.
> 
> Afterwards, does something like`docker run -it --rm cirrusci/windowsservercore:2019` work?

*Offtopic, sorry: I hate Windows, their containers just don't work on Linux, it's pretty hard to setup this OS in Virtual Machine with Docker, and even this not enough: you have to switch something to get Win containers work on Windows!*

---

Thank you, it helped.

A little feedback, suggestion: the stage `Preparing volume to work with...` (with `simple` output) taken a long time (around 15 minutes) with intense Network, Disk and RAM loads by `dockerd.exe`, and it's not obvious what exactly happens, I'd like to see details, maybe more steps/stages, or even maybe we can add some progress bar.

---

UPD: Oh, before sending I've decided to wait for a result and I've got an error:

```
Preparing volume to work with...
Failed to create a volume from working directory: working volume creation failed: when starting helper container: Error response from daemon: hcsshim::CreateComputeSystem 086dfb4ffbb74b69a6888c5918f7a311c517b1d1267baa5edeee679d994934de: hcsshim: timeout waiting for notification
(extra info: {"SystemType":"Container","Name":"086dfb4ffbb74b69a6888c5918f7a311c517b1d1267baa5edeee679d994934de","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\086dfb4ffbb74b69a6888c5918f7a311c517b1d1267baa5edeee679d994934de","Layers":[{"ID":"fa180a98-e574-540d-abd9-a3cfd8c9aa96","Path":"C:\\ProgramData\\Docker\\windowsfilter\\4fef1ceb26e28197e7e2f7f07c7534bc6574953562396172d21861e09128d693"},{"ID":"5a06e858-d7dc-5fe6-8053-50908209034d","Path":"C:\\ProgramData\\Docker\\windowsfilter\\70cdf3c3c9376de7632bfc96f186800c2b2e18d9128003870cd3e328a3298d8b"}],"HostName":"086dfb4ffbb7","MappedDirectories":[{"HostPath":"C:\\ProgramData\\Docker\\volumes\\cirrus-agent-volume-47a189aa-3790-4533-a3a3-0ecba037cdbb\\_data","ContainerPath":"C:\\agent-volume","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"Z:\\linux\\Projects\\ruby\\filewatcher","ContainerPath":"C:\\project-host","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"C:\\ProgramData\\Docker\\volumes\\cirrus-working-volume-47a189aa-3790-4533-a3a3-0ecba037cdbb\\_data","ContainerPath":"C:\\project-volume","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true,"EndpointList":["fc223f24-f930-4c6f-ae36-7a0bdea5c68d"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\4fef1ceb26e28197e7e2f7f07c7534bc6574953562396172d21861e09128d693\\UtilityVM"},"AllowUnqualifiedDNSQuery":true})
'Preparing execution environment...' failed in 29:08!
Error: working volume creation failed: when starting helper container: Error response from daemon: hcsshim::CreateComputeSystem 086dfb4ffbb74b69a6888c5918f7a311c517b1d1267baa5edeee679d994934de: hcsshim: timeout waiting for notification
(extra info: {"SystemType":"Container","Name":"086dfb4ffbb74b69a6888c5918f7a311c517b1d1267baa5edeee679d994934de","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\086dfb4ffbb74b69a6888c5918f7a311c517b1d1267baa5edeee679d994934de","Layers":[{"ID":"fa180a98-e574-540d-abd9-a3cfd8c9aa96","Path":"C:\\ProgramData\\Docker\\windowsfilter\\4fef1ceb26e28197e7e2f7f07c7534bc6574953562396172d21861e09128d693"},{"ID":"5a06e858-d7dc-5fe6-8053-50908209034d","Path":"C:\\ProgramData\\Docker\\windowsfilter\\70cdf3c3c9376de7632bfc96f186800c2b2e18d9128003870cd3e328a3298d8b"}],"HostName":"086dfb4ffbb7","MappedDirectories":[{"HostPath":"C:\\ProgramData\\Docker\\volumes\\cirrus-agent-volume-47a189aa-3790-4533-a3a3-0ecba037cdbb\\_data","ContainerPath":"C:\\agent-volume","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"Z:\\linux\\Projects\\ruby\\filewatcher","ContainerPath":"C:\\project-host","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"C:\\ProgramData\\Docker\\volumes\\cirrus-working-volume-47a189aa-3790-4533-a3a3-0ecba037cdbb\\_data","ContainerPath":"C:\\project-volume","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true,"EndpointList":["fc223f24-f930-4c6f-ae36-7a0bdea5c68d"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\4fef1ceb26e28197e7e2f7f07c7534bc6574953562396172d21861e09128d693\\UtilityVM"},"AllowUnqualifiedDNSQuery":true})
2021/04/23 01:34:37 working volume creation failed: when starting helper container: Error response from daemon: hcsshim::CreateComputeSystem 086dfb4ffbb74b69a6888c5918f7a311c517b1d1267baa5edeee679d994934de: hcsshim: timeout waiting for notification
(extra info: {"SystemType":"Container","Name":"086dfb4ffbb74b69a6888c5918f7a311c517b1d1267baa5edeee679d994934de","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\086dfb4ffbb74b69a6888c5918f7a311c517b1d1267baa5edeee679d994934de","Layers":[{"ID":"fa180a98-e574-540d-abd9-a3cfd8c9aa96","Path":"C:\\ProgramData\\Docker\\windowsfilter\\4fef1ceb26e28197e7e2f7f07c7534bc6574953562396172d21861e09128d693"},{"ID":"5a06e858-d7dc-5fe6-8053-50908209034d","Path":"C:\\ProgramData\\Docker\\windowsfilter\\70cdf3c3c9376de7632bfc96f186800c2b2e18d9128003870cd3e328a3298d8b"}],"HostName":"086dfb4ffbb7","MappedDirectories":[{"HostPath":"C:\\ProgramData\\Docker\\volumes\\cirrus-agent-volume-47a189aa-3790-4533-a3a3-0ecba037cdbb\\_data","ContainerPath":"C:\\agent-volume","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"Z:\\linux\\Projects\\ruby\\filewatcher","ContainerPath":"C:\\project-host","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"C:\\ProgramData\\Docker\\volumes\\cirrus-working-volume-47a189aa-3790-4533-a3a3-0ecba037cdbb\\_data","ContainerPath":"C:\\project-volume","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true,"EndpointList":["fc223f24-f930-4c6f-ae36-7a0bdea5c68d"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\4fef1ceb26e28197e7e2f7f07c7534bc6574953562396172d21861e09128d693\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}) 
```

Do you have thoughts about reasons? 8 GB RAM and 4 cores were busy around 50%, but disk space (40 GB) was almost full sometimes (3 GB free left).

**Comment by edigaryev** [comment]
>with intense Network, Disk and RAM loads by `dockerd.exe`

Looks like it's pulling (and possibly unpacking) the image, which for Windows Containers are pretty huge. Also an issue similar to https://github.com/cirruslabs/cirrus-ci-agent/issues/128 might come into play by slowing everything down.

>`hcsshim: timeout waiting for notification`

Seems to be some internal issue with Docker talking to Windows Containers that's still persists to this day: https://github.com/microsoft/hcsshim/issues/152.

> Do you have thoughts about reasons? 8 GB RAM and 4 cores were busy around 50%, but disk space (40 GB) was almost full sometimes (3 GB free left).

I'd say try running `docker run -it --rm cirrusci/windowsservercore:2019` first to see if Windows Containers work at all.

**Comment by AlexWayfer** [comment]
> > with intense Network, Disk and RAM loads by `dockerd.exe`
> 
> Looks like it's pulling (and possibly unpacking) the image, which for Windows Containers are pretty huge. Also an issue similar to [cirruslabs/cirrus-ci-agent#128](https://github.com/cirruslabs/cirrus-ci-agent/issues/128) might come into play by slowing everything down.

I've disabled Defender, and there is no "Antimalware" program in Task Manager.

The suggested command from mentioned issue returns the error:

```
Set-MpPreference : A general error occurred that is not covered by a more specific error code.
At line:1 char:1
+ Set-MpPreference -DisableRealtimeMonitoring 1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_MpPreference:root\Microsoft\...FT_MpPreference) [Set-MpPreference],
   CimException
    + FullyQualifiedErrorId : HRESULT 0x800106ba,Set-MpPreference    
```



> > `hcsshim: timeout waiting for notification`
> 
> Seems to be some internal issue with Docker talking to Windows Containers that's still persists to this day: [microsoft/hcsshim#152](https://github.com/microsoft/hcsshim/issues/152).

Thank you, I subscribed, that's sad.

> > Do you have thoughts about reasons? 8 GB RAM and 4 cores were busy around 50%, but disk space (40 GB) was almost full sometimes (3 GB free left).
> 
> I'd say try running `docker run -it --rm cirrusci/windowsservercore:2019` first to see if Windows Containers work at all.

I've got an error about free space and resized the image.

After a long time I've got the same `hcsshim: timeout waiting for notification`. I didn't find a work-around in the mentioned issue, so… thank you, I'm going to close this issue as the problem is in third-party stuff.
