### ISSUE TITLE
Persistent worker failed to start the task: Parallels isolation failed

### ISSUE THREAD

**Issue by real-or-random** [cirruslabs/cirrus-cli#373]
https://cirrus-ci.com/task/4823373415972864
https://cirrus-ci.com/task/6102191808184320
https://cirrus-ci.com/task/4694816924631040

from https://github.com/bitcoin-core/secp256k1/pull/925 and https://github.com/bitcoin-core/secp256k1/pull/926

**Comment by fkorotkov** [comment]
It does seem like a false alarm. @edigaryev seems it's hitting this case https://github.com/golang/crypto/blob/83a5a9bb288b4c9523e182ed4f621411a11de3df/ssh/session.go#L456-L460. 

I've fixed the issue on the server side: now Cirrus ignores failures from the persistent worker in case of a task being already in a final state. In @real-or-random cases all the tasks finished successfully but then CLI reported the failure.

@edigaryev once you are back from PTO next week let's think if CLI should just ignore `ExitMissingError`.

**Comment by real-or-random** [comment]
Thanks for the quick fixes again!

Sorry, here's another failure:
https://cirrus-ci.com/task/6378104290541568
Not sure if this is related or not. The error message is different but it shows the same behavior of marking a task failed even though it has run successfully.

Maybe this is already fixed here but the fixed is simply not deployed? If yes, ignore me.

**Comment by fkorotkov** [comment]
@real-or-random this is a bit different issue. Seems there was an issue while updating `clone` command status (this is why it's reported as failed). It caused a confusion between service that is responsible for status updates of tasks/builds and the service that runs persistent workers.

I've fixed the issue. Sorry for the inconvenience!

**Comment by real-or-random** [comment]
> I've fixed the issue. Sorry for the inconvenience!

Thanks!
