### ISSUE TITLE
Way to generate fixtures for `cirrus internal test`

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#381]
It will be great to have an option to just generate `.cirrus.expected.yml` and `.cirrus.expected.log` right from the `cirrus internal test`. Maybe with a flag like `--generate-expected`. So it will be very easy to generate fixtures with `cirrus internal test --generate-expected`

**Comment by edigaryev** [comment]
Right now `cirrus internal test` test discovery works by locating the directories with the `.cirrus.expected.yml` file.

Any idea how else we can figure out that a directory with a `.cirrus.star` is a test?

**Comment by fkorotkov** [comment]
Maybe let's do it as we have internally for Cirrus? Just a way to update a fixture so anyone can create empty `.cirrus.expected.yml` first and run `cirrus internal test --generate-expected`. Maybe the flag even can be called `--update-expected` then. What do you think?

**Comment by edigaryev** [comment]
Related issue that might help in determining the right way to do it: https://github.com/cirruslabs/cirrus-cli/issues/354.
