### ISSUE TITLE
Calls to FS should be cached within a Starlark evaluation

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#391]
We should assume that FS is immutable for a Starlark evaluation and cache results of the FS operations. It should help in case of a GitHub-backed FS to not execute same requests over and over again.

**Comment by edigaryev** [comment]
> We should assume that FS is immutable for a Starlark evaluation and cache results of the FS operations. It should help in case of a GitHub-backed FS to not execute same requests over and over again.

I assume something bounded like a LRU cache will do, because otherwise we have a memory/disk problem.

**Comment by fkorotkov** [comment]
I don't think it's a problem within a single evaluation. Just invalidating the whole cache should be fine. I'm thinking just having an instance that implements `FileSystem` and can wrap a `FileSystem` instance, which can wrap an instance that passed to `loader.NewLoader`.

**Comment by edigaryev** [comment]
> I don't think it's a problem within a single evaluation. Just invalidating the whole cache should be fine.

What I've meant is that it would be technically possible to allocate e.g. a 500 megabytes of memory by downloading different 10 megabyte blobs from GitHub this way (maximum REST API limit AFAIR). Now imagine there are multiple evaluations are started on a single CLI instance 🤔
