### ISSUE TITLE
Implement --affected-files-from-git flag

### ISSUE THREAD

**Issue by edigaryev** [cirruslabs/cirrus-cli#437]
Suggested in https://github.com/cirruslabs/cirrus-cli/pull/434#pullrequestreview-708764688:

Related to #433.

Example usage, to include files changed since specific revision or tag:

```
cirrus run --affected-files-git 2572ec1
```

```
cirrus run --affected-files-git v0.58.0
```

**Comment by fkorotkov** [comment]
HEAD^ notation should be also supported 👌
