### ISSUE TITLE
re.findall pattern error

### ISSUE THREAD

**Issue by SeanTAllen** [cirruslabs/cirrus-cli#443]
I tried using `re.findall` and the following works:

```
re.findall("h", "hello")
```

however introducing `\` causes a failure. an example:

```
re.findall('1\.1', 'foo')
```

will end up with a parse configuration error. I didn't see if all normal python regex patterns work. I do know that `\` will break everything.

**Comment by edigaryev** [comment]
You need to [double escape the backslash](https://stackoverflow.com/questions/13989640/regular-expression-to-match-a-dot#comment117849370_13989661):

```python
re.findall('1\\.1', 'foo')
```

Or use a raw string literal:

```python
re.findall(r'1\.1', 'foo')
```

[Starlark specification on string escapes](https://github.com/google/starlark-go/blob/master/doc/spec.md#string-escapes) might be also helpful.

**Comment by SeanTAllen** [comment]
Thanks
