### ISSUE TITLE
Include COPY and ADD values in the Docker builder cache key

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#447]
Since now the `.cirrus.yml` parsing is done in Go we can try to integrate https://github.com/moby/buildkit in order to parse Dockerfile used for Dockerfile-as-CI-enviroment feature.

I think the right course of actions will be to add warnings if people use a "wildcard" COPY/ADD like `COPY secrets/`. But in case of COPY-ing/ADD-ing just files, include them into the fingerprint.

**Comment by fkorotkov** [comment]
We might also need to add a new field to `EvaluateConfigResponse` with hashes for all `Dockerfile`s used because a `gke_container` can come in the `additional_instances_info` and we'd still want to get info about the `dockerfile` field there.

```proto
message DockerfileInfo {
  string path = 1;
  map<string, string> arguments = 2;
  string fingerprint = 3;
}
```

**Comment by anarazel** [comment]
@edigaryev There's still a note about the danger of using ADD and COPY in the docs:
```
Danger of using COPY and ADD instructions

Cirrus doesn't include files added or copied into a container image in the cache key. This means that for a public repository a potential bad actor can create a PR with malicious scripts included into a container, wait for it to be cached and then reset the PR so it looks harmless.
```

That's obsolete now, right?
