### ISSUE TITLE
dockerfile hash computation doesn't handle COPY of directories nor windows path seps

### ISSUE THREAD

**Issue by anarazel** [cirruslabs/cirrus-cli#478]
Hi,

Despite https://github.com/cirruslabs/cirrus-cli/pull/452 I see containers not being rebuilt. A bit of debugging later shows that this happens at least in the case where COPY copies a directory, rather than a file.
An example of this is (in a debugging repo):  https://cirrus-ci.com/build/5938448480600064 didn't rebuild the 'linux' container, despite a copied file changing.

After changing the COPY to copy files separately, the hash computation appears to work: https://cirrus-ci.com/build/5739968847937536

Even when using individual files I see windows dockerfiles not getting rebuilt. See https://cirrus-ci.com/build/5808529746427904 - that turns out to be because I did COPY path\to\file target/. It does appear to work after converting those to forwards slashes: https://cirrus-ci.com/build/5904551994720256

Regards,

Andres

**Comment by edigaryev** [comment]
Hi Andres! 👋 

Thanks for reporting this! This will be addressed by https://github.com/cirruslabs/cirrus-cli/pull/479.
