### ISSUE TITLE
Starlark Configuration Testing

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#48]
Since Starlark is a real language we need to figure out a testing scenario for `.cirrus.star` file. Ideally there should be a way to provide environment variables and see what kind of YAML config Starlark will output.

Should it be a part of `validate` command? How to mock file system access?

Creating this issue to brainstorm possible options.

My main use case can be described like that: we'll have github.com/cirrus-templates/node template that will generate either `yarn` specific or `npm` specific tasks depending on files in the repository. How can we test this template?

**Comment by edigaryev** [comment]
@fkorotkov isn't this a duplicate of already resolved https://github.com/cirruslabs/cirrus-cli/issues/95?

**Comment by fkorotkov** [comment]
Yes!
