### ISSUE TITLE
Cirrus-cli uses v1.73.1 of cirrus-ci-agent

### ISSUE THREAD

**Issue by nbyavuz** [cirruslabs/cirrus-cli#485]
Hi, 

Thanks for OpenBSD / NetBSD support!

When I set VMs as a persistent worker, tasks are failing with:
`failed to download agent: got HTTP code 404 when downloading https://github.com/cirruslabs/cirrus-ci-agent/releases/download/v1.73.1/agent-openbsd-amd64`

OpenBSD / NetBSD are both available on v1.73.2.

Could you patch cirrus-cli to use  v1.73.2 of cirrus-ci-agent?

Thanks!

**Comment by edigaryev** [comment]
Hello and thanks for reporting this! 👋

This should now be now fixed for Persistent Workers, while the fix for the `cirrus run` is on the way (see #486).
