### ISSUE TITLE
Report annotations in logs when executed in GHA

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#489]
It's possible to report errors/warnings/etc via [log statements in GHA](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-a-warning-message). Right now the CLI itself ignores any reported annotations but we can start logging them when CLI's output format set to `github`.

**Comment by edigaryev** [comment]
To clarify: this is about annotations retrieved via executor's RPC.
