### ISSUE TITLE
Improve rolling updates of persistent workers

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#490]
To make rolling updates it will make sense to add two more sub-commands to `worker` command:

1.  `cirrus worker pause --wait` which will use auth token from the config and call a new gRPC method to pause itself. `--wait` argument of the command will indicate that the worker should call another new gRPC method to get status of itself and wait for all tasks to finish.
2. `cirrus worker resume` will call yet another gRPC method to unpause the worker and start serving requests to process tasks.

These methods will help to manage rolling updates of persistent workers without service interruption.

**Comment by edigaryev** [comment]
What do you think about implementing a graceful shutdown on `SIGTERM` instead? Upon receiving this signal, the agent will stop polling for new tasks and wait for the current tasks to complete.

It's also possible to [`wait_for`](https://stackoverflow.com/a/46541018/9316533) for the process in Ansible, for example, which is effectively provides a `--wait` option above.

**Comment by fkorotkov** [comment]
I think it's still a tricky. In our use case for Mac Mini workers we have the worker being a daemon. We might need to restart hosts for updates and we don't want the daemon to start. A graceful shutdown on `SIGTERM` still seems reasonable but I think the `pause`/`resume` subcommands might still be useful for rolling updates.
