### ISSUE TITLE
Permissions of files in working directory aren't preserved when copied

### ISSUE THREAD

**Issue by mkenigs** [cirruslabs/cirrus-cli#528]
I have a file with permissions `-rw-------` in my working directory, but checking them in the VM they are `-rw-r--r--`

**Comment by mkenigs** [comment]
Oh okay, any reason not to use `rsync -p`?

**Comment by mkenigs** [comment]
That makes sense. Yeah you're right, I'm not doing it that way in the cloud; I was using an ssh key not checked into git, which I'll use an encrypted env var for in the cloud.

**Comment by fkorotkov** [comment]
Good point, @edigaryev. Let's close it then. I also think there might be an issue with what kind of permissions to do when you run Cirrus CLI on Windows, for example.

**Comment by mkenigs** [comment]
(for posterity I'm guessing a local workaround is --dirty)
