### ISSUE TITLE
Persistent workers: support Dockerfile

### ISSUE THREAD

**Issue by 0xxon** [cirruslabs/cirrus-cli#541]
Hi,

I just wanted to check if there is a reason that persistent workers don't support a Dockerfile when using containers, but only specific images.

For our use-case, being able to use a Dockerfile would be great - we want to basically move some CPU intensive tests from cirrus machines to our own infrastructure - while keeping the way the tests are run as compatible as possible.

**Comment by fkorotkov** [comment]
I guess you are looking for something like:

```yaml
persistent_worker:
  isolation:
    container:
      dockerfile: .ci/Dockerfile
```

I think it's pretty doable but we'll need to check internals. Also I see a problem that different persistent workers will have the containers built at different times which might not be ideal for reproducibility. But Persistent Workers are associated with the same reproducibility challenges already so it might not be that big of a deal....

**Comment by 0xxon** [comment]
Yup, that is exactly what we are looking for.

At least for us it does not matter at all that different persistent workers will build the containers at different times.
