### ISSUE TITLE
[tart] use folder sharing for local runs

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#554]
Plus it will allow to support --dirty mode.

Not that for the persistent worker isolation we can continue using "scp" because we just copy over the agent binary which is one file and not so large.

**Comment by edigaryev** [comment]
Reopening to add support for faster working directory sync using folder sharing in the future, see https://github.com/cirruslabs/cirrus-cli/pull/557#pullrequestreview-1097683236.

**Comment by fkorotkov** [comment]
IMO it's fine to leave just the very fast `--dirty` option.
