### ISSUE TITLE
Sentry Integration

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#587]
This is master issue for Sentry integration across Cirrus CLI, Cirrus Agent, Tart and Softnet.

Let's integrate Sentry for error and performance monitoring across our stack for persistent workers. The challenging part here will be basically doing [distributed tracing](https://docs.sentry.io/product/sentry-basics/tracing/) but on a single host across 4 components in different languages. Some context like span id will be required to be passed down (for example, from CLI to Tart and from Tart down to Softnet).

**Comment by edigaryev** [comment]
Resolved by https://github.com/cirruslabs/cirrus-ci-agent/pull/264, https://github.com/cirruslabs/tart/pull/352, https://github.com/cirruslabs/cirrus-cli/pull/589 and https://github.com/cirruslabs/softnet/pull/13.
