### ISSUE TITLE
Complete the parser

### ISSUE THREAD

**Issue by edigaryev** [cirruslabs/cirrus-cli#59]
#58 introduces a YAML parser that's able to run most of the CLI tasks without network connection.

However, this results in at least two parsers in-the-wild (the other being the one that processes `.cirrus.yml` in the cloud). To avoid the divergence in the future, it might be a good idea to consolidate everything as a CLI package, which is available for use in any Go program.

To do this, the following things need to be implemented:

* support all execution environments
* support JSON Schema
* integrate already existing tests

**Comment by fkorotkov** [comment]
Almost everything done except JSON schema. Created a separate issue https://github.com/cirruslabs/cirrus-cli/issues/148
