### ISSUE TITLE
Release is missing some assests

### ISSUE THREAD

**Issue by hamzaremmal** [cirruslabs/cirrus-cli#612]
When following the [guide](https://github.com/cirruslabs/cirrus-cli/blob/master/INSTALL.md#prebuilt-binary) to install cirrus-cli on my machine, I've noticed a small problem related to the assests of the latest release ([v.0.96.1](https://github.com/cirruslabs/cirrus-cli/releases/tag/v0.96.1)). 

The one-liner command fetch the corresponding executable from the latest release, therefore, the installation didn't work when trying it. I had to download an older version ([v.0.96.0](https://github.com/cirruslabs/cirrus-cli/releases/tag/v0.96.0)) by changing the command to 
```bash
curl -L -o cirrus https://github.com/cirruslabs/cirrus-cli/releases/download/v0.96.0/cirrus-linux-amd64   && sudo mv cirrus /usr/local/bin/cirrus && sudo chmod +x /usr/local/bin/cirrus
```

**Comment by edigaryev** [comment]
Hello Hamza 👋 

It seems that the integration tests had flaked and blocked the release of binaries, I've restarted the build and this should be fixed now. Thanks for reporting!
