### ISSUE TITLE
container results in arm64 image on MacOS Cirrus CLI, but amd64 in Cirrus CI

### ISSUE THREAD

**Issue by YOU54F** [cirruslabs/cirrus-cli#621]
Hey team,

Love the work on tart and cirrus 👍🏾 

I have an issue which has been causing me difficulties in creating the same test runs locally on an m1 mac, and Cirrus CLI.

I am trying to run two container tasks, one for `amd64` one for `arm64`.

1. Cirrus CLI does not support `arm_container`
2. Cirrus CLI does not respect the fact the `container` in a task, should relate to an `amd64` platform.

## .cirrus.yml

```
arm_container_task: 
  arm_container:
    image: ubuntu:latest
  pre_req_script: uname -a

x64_container_task:
  container:
    image: ubuntu:latest
  pre_req_script: uname -a
```

## Actual Result

1. `arm_container` is skipped
2. `container` task incorrectly runs on `arm64` when invoked from MacOS M1

```
Started 'arm_container' task
'arm_container' task skipped in 0.0s!
Started 'x64_container' task
Started 'Preparing execution environment...'
Preparing volume to work with...
'Preparing execution environment...' succeeded in 1.2s!
Started 'image pull'
Pulling image ubuntu:latest...
'image pull' succeeded in 3.1s!
Started 'pre_req' script
uname -a
Linux 8f2dd76c0e80 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
'pre_req' script succeeded in 1.0s!
'x64_container' task succeeded in 5.7s!
```

![Screenshot 2023-05-22 at 11 32 30](https://github.com/cirruslabs/cirrus-cli/assets/19932401/46828026-dcd8-4586-acd1-9b3596fbbc80)

## Expected Result

1. `arm_container` task can run and is locked to platform `arm64`
2. `container` task can run and is locked to platform `amd64`

```
Started 'arm_container' task
Started 'Preparing execution environment...'
Preparing volume to work with...
'Preparing execution environment...' succeeded in 1.2s!
Started 'image pull'
Pulling image ubuntu:latest...
'image pull' succeeded in 3.1s!
Started 'pre_req' script
uname -a
Linux 8f2dd76c0e80 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
'pre_req' script succeeded in 1.0s!
'arm_container' task succeeded in 5.7s!


Started 'x64_container' task
Started 'Preparing execution environment...'
Preparing volume to work with...
'Preparing execution environment...' succeeded in 1.2s!
Started 'image pull'
Pulling image ubuntu:latest...
'image pull' succeeded in 3.1s!
Started 'pre_req' script
uname -a
Linux 8f2dd76c0e80 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
'pre_req' script succeeded in 1.0s!
'x64_container' task succeeded in 5.7s!
```

## Have I tried to build it?

Yes, of sorts, adding in the `Platform` into `backend.cli.ImageBuild` of `amd64` at least got my containers fixed to x86_64

1. https://github.com/cirruslabs/cirrus-cli/blob/21e0ceb6383c3ab6166a406d82d492b8272085c0/internal/executor/instance/instance.go#LL92C6-L92C6

2. https://github.com/cirruslabs/cirrus-cli/blob/master/internal/executor/instance/containerbackend/docker.go#L130-L135

```
		buildProgress, err := backend.cli.ImageBuild(ctx, tarball, types.ImageBuildOptions{
			Tags:       input.Tags,
			Dockerfile: input.Dockerfile,
			BuildArgs:  pointyArguments,
			Remove:     true,
			PullParent: input.Pull,
			Platform:   input.Architecture,
		})
```

**Comment by fkorotkov** [comment]
At the moment `arm_container` is not supported in Cirrus CLI. It's a cloud-only feature and locally CLI is not trying to mach behavior you described.

What are you trying to achieve? Running Cirrus CLI in some other CI? Or just trying to reproduce some `amd64` build locally?

**Comment by YOU54F** [comment]
Hey dude,

I would expect cirrus-cli to run `container` tasks defined in a cirrus yaml to match cirrus ci

>Note: Cirrus CLI only supports [Linux container](https://cirrus-ci.org/guide/linux/#linux-containers) and [macos_instance VMs](https://cirrus-ci.org/guide/macOS/) at the moment. Linux containers support the [Dockerfile as a CI environment](https://cirrus-ci.org/guide/docker-builder-vm/#dockerfile-as-a-ci-environment) feature.

so that if you run it on a mac m1 machine, the images are amd64 images, as they would be on cirrus-ci

I would like to provide users of our open source libraries to run the same image/conditions locally with Cirrus-CLI as per the behaviour on Cirrus CLI.

running this task on a mac m1

```
x64_container_task:
  container:
    image: ubuntu:latest
  pre_req_script: uname -a
```

to me, imo, incorrectly returns `aarch64`.

This is an issue as we install platform specific binaries into our images (we cross distribute binaries, and cirrus ci allows us the ability to test arm64 versions, we use GitHub actions for amd64)

**Comment by YOU54F** [comment]
>At the moment arm_container is not supported in Cirrus CLI. It's a cloud-only feature and locally CLI is not trying to mach behavior you described.

I'd love to see arm_container supported via the platform flag, either via emulation on non arm64 platforms, or natively on arm64 platforms.

I have amd64 machines, so the only real use case I want if 

- mac arm machine running a `container` task returns `x86_64`
- arm machine running a `arm_container` task returns `aarch64`

This is the workflow I am running in Cirrus which works nicely, but running the container tasks locally on the m1 return unexpected results 

https://github.com/YOU54F/pact-ruby-standalone/blob/441ee1d55bcc08f33a80fbda1c4f479c19478770/.cirrus.yml#L124-L155

Here are the binaries we produce and want to test

https://github.com/YOU54F/pact-ruby-standalone/releases/tag/v2.2.1 

:)

I have additional use cases for personal stuff, but this is mainly to unify behaviour between cirrus cli and cirrus ci, so a new user being introduced to both, doesn't get unexpected behaviour.

I've been drafting a post about our CI systems, and mentioned Cirrus CI as our default for arm64, but had to mention this gotcha when running locally

https://github.com/pact-foundation/docs.pact.io/pull/264/files#diff-ddfef7524b275e3d16ebac827420128e80f18c1f42c0bc0df28ba274ed593ee3R190-R198

**Comment by YOU54F** [comment]
Not sure if you are familiar with the [act](https://github.com/nektos/act) project?

They cover this case with the following, but only as GitHub Actions doesn't support ARM64 processors, this is where both cirrus ci and cirrus cli shine (you can cover both cases, which makes is incredibly appealing for local and remote cross platform testing :) )

```
WARN  ⚠ You are using Apple M1 chip and you have not specified container architecture, you might encounter issues while running act. 
If so, try running it with '--container-architecture linux/amd64'.
```
