### ISSUE TITLE
Persistent worker: Support isolation via VM for non-macos operating systems

### ISSUE THREAD

**Issue by anarazel** [cirruslabs/cirrus-cli#638]
Hi,

The ability to start virtual machines for persistent runner jobs on macOS is very nice - unfortunately persistent workers on other operating systems don't support the same. For an internal project the container boundaries might suffice, but for an open source project excepting pull requests that doesn't feel sufficient isolation.

I can see a few different ways of supporting this.

1) Have something like a 'cirrus worker run --once' option, that'd just run one build and then exit. It'd be the responsibility of the whatever the started the worker to reset the worker subsequently. That's not perfect, because of course a CI job could have tried to interfere with the persistent worker shutting down. But I assume it'd be fairly easy to implement.

2) Allow persistent workers to specify a command that's used to start the actual execution of a task. It'd be the responsibility of that command to start a vm and trigger execution of the agent.

3) Provide a different isolation backend that starts virtual machines via libvirt (or something similar). That'd be more work, but obviously also more flexible.

Does any of that sound realistic?

Regards,

Andres

**Comment by fkorotkov** [comment]
We are actually planning to work on something like [Tart](https://github.com/cirruslabs/tart) but for Linux platform which looks like option 3. We did some theoretical research and planning to start working on a prototype soon. Can't give any ETAs but this work is in the top of our priorities.

**Comment by fkorotkov** [comment]
BTW there is [`container` isolation](https://cirrus-ci.org/guide/persistent-workers/#container) but I guess you are more interested in VMs.

**Comment by anarazel** [comment]
A related issue: It doesn't look like there is a way to force use of tart isolation when running a persistent worker? For open source projects, and even beyond, it seems like it'd often be important to define the restrictions in the persistent worker config, rather than in a project's .cirrus.yml (which can be modified in pull requests etc).

**Comment by fkorotkov** [comment]
Sounds reasonable. Could you please create a separate issue for such persistent worker setting?

**Comment by fkorotkov** [comment]
Hey @anarazel, we just release `0.108.0` version of the CLI which now supports isolation via Vetu on Linux hosts. PTAL https://github.com/cirruslabs/vetu
