### ISSUE TITLE
Error: ssh: session already started

### ISSUE THREAD

**Issue by pengpengdai** [cirruslabs/cirrus-cli#666]
**.cirrus.yml config**
persistent_worker:
  isolation:
    tart:
      image: macos-14-xcode-15-vm
      user: admin
      password: admin
      volumes:
          - name: mtest
            source: /Users/huolala/mtest
            target: mtest
            readonly: true
          - name: cocoapods-repo
            source: /Users/huolala/.cocoapods
            target: cocoapods-repo
            readonly: true
  script: true

task:
  script:
    - pwd
    - ls /Volumes/My\ Shared\ Files/cocoapods-repo
    - sleep 100

**cirrus run failed**
➜  cirrus cirrus run
🕘 'main' task 13s
   ✅ pull virtual machine 0.0s
   ✅ clone virtual machine 0.0s
   ✅ boot virtual machine 7.4s
   ✅ syncing working directory 0.5s
   🕘 symlinking volume mounts 1.4s
      running command: ln -s "/Volumes/My Shared Files/mtest" "mtest"
      running command: ln -s "/Volumes/My Shared Files/cocoapods-repo" "cocoapods-repo"
      
Error: ssh: session already started
2023/11/20 20:29:08 ssh: session already started
➜  cirrus

question
1. Why do I get an error when I only mount two directories? Is there something wrong with my configuration?
2. For macos, is there any better way to mount the file directory? I think the directory of the physical machine should be mounted to the directory specified by the virtual machine instead of the directory of /Volumes/My Shared Files.

**Comment by edigaryev** [comment]
Hello, thanks for reporting this!

The issue is now fixed in https://github.com/cirruslabs/cirrus-cli/pull/668 and will be available as a part of [`0.107.2` release](https://github.com/cirruslabs/cirrus-cli/releases/tag/v0.107.2) shortly.
