### ISSUE TITLE
OTEL metric of VM startup time

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#685]
Get sense of how long it takes from getting a request to start a VM to start executing agent inside the VM. Might require couple metrics to narrow down bottlenecks.

**Comment by edigaryev** [comment]
I think this could already be accomplished by checking the `upload-and-wait-for-agent` span start time:

<img width="1197" alt="Screenshot 2024-02-14 at 11 44 56" src="https://github.com/cirruslabs/cirrus-cli/assets/85709/f83d0789-1818-44b4-a680-80f1cb9fc0b7">

The only issue is that this "start time" cannot be directly queried by the [TraceQL](https://github.com/grafana/tempo/blob/main/docs/design-proposals/2022-04%20TraceQL%20Concepts.md) (it only has `duration` for now), so we'll probably have to wrap the whole starting procedure in one more span to be able to query this value directly and graph it on the dashboards.
