### ISSUE TITLE
Warm Isolation for Persistent Worker

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#697]
It will be great if before Persistent Worker pull for new tasks it can warm up a preconfigured isolation. I propose to plug this logic in this line:

https://github.com/cirruslabs/cirrus-cli/blob/0b9ed560488909bf0b4802638cb157ac33e825a7/internal/worker/task.go#L56

To have a "warm" isolation configured and see if we need to reuse the warm instance or stop it and create a new one. Worker will also make sure to warm and instance before polling an upstream.

**Comment by edigaryev** [comment]
It seems that this was already implemented in https://github.com/cirruslabs/cirrus-cli/pull/698, so closing.
