### ISSUE TITLE
[Request] Option to customize SSH port

### ISSUE THREAD

**Issue by ncs29** [cirruslabs/cirrus-cli#708]
This request is for an option to customize the SSH port to the while connecting to the instance

A similar request was [recently merged](https://github.com/cirruslabs/gitlab-tart-executor/pull/69) to gitlab-tart-executor. Having this in the CLI allows to reuse the CI images locally for testing.

**Comment by edigaryev** [comment]
Hello Navneeth!

Please check out [the new `0.115.0` version](https://github.com/cirruslabs/cirrus-cli/releases/tag/v0.115.0) that was just released.

It allows you to specify `port:` field in the Tart/Vetu instances.
