### ISSUE TITLE
Allow to `cirrus run` the task by ID, even when name is present

### ISSUE THREAD

**Issue by bartekpacia** [cirruslabs/cirrus-cli#713]
Assumption: my `.cirrus.yaml` has the following tasks:

```yaml
deploy_android_app_task:
  name: Deploy Android app to Google Play
  # ...
deploy_ios_app_task:
  name: Deploy iOS app to App Store
  # ...
```

### Current behavior

When a task has `name` specified, it can only be run by its name:

```
$ cirrus run deploy_android_app
Error: task filter yielded no matches: none of the 2 task(s) were matched using a "deploy_android_app" filter
2024/04/07 15:50:08 task filter yielded no matches: none of the 2 task(s) were matched using a "deploy_android_app" filter
```

```
$ cirrus run 'Deploy Android app to Google Play'
# works
```

### Expected behavior

Both task's ID and task's name can be used to run the task:

```
$ cirrus run deploy_android_app
# works
```

```
$ cirrus run 'Deploy Android app to Google Play'
# works
```

**Comment by fkorotkov** [comment]
Right now `deploy_android_app` is assigned to `name` which is getting overriden. I think the easies non-breaking change for this will be to assign prefixes of `*_task` to both `name` and `alias` of the tasks. This way `cirrus run deploy_android_app` will work in this scenario. @edigaryev WDYT?

**Comment by edigaryev** [comment]
@fkorotkov:

Perhaps we could even introduce a new property named `adhoc_name` in the `Task.Metadata.Properties` (similarly to `alias`) and consider that name too in the `taskfilter.MatchExactTask()`.

This way the user will get more predictable results, as this logic would work even in the presence of `name:` and `alias:` in the task.

@bartekpacia:

Do you still want this feature after the https://github.com/cirruslabs/cirrus-cli/pull/716 got merged?

**Comment by bartekpacia** [comment]
> Do you still want this feature after the https://github.com/cirruslabs/cirrus-cli/pull/716 got merged?

Just now I learned that [a task can also have an alias](https://cirrus-ci.org/guide/writing-tasks/#task-execution-dependencies) – which is great. Therefore a title of this PR should probably read "Allow to cirrus run the task by _alias_, even when name is present".

Initially I was thinking that it would be "cleaner" if a task had both `name` and `id`, but having alias fulfills the same purpose as an id, I think.
