### ISSUE TITLE
[Request] Option to change mount dir when running with `--dirty` flag

### ISSUE THREAD

**Issue by ncs29** [cirruslabs/cirrus-cli#720]
When using Cirrus CLI with Tart (Ventura VM), specifying the `--dirty` flag mounts the current host working dir to `/Volumes/My Shared Files/working-dir`. As this path contains spaces, some of the bash scripts that we use fail, as the string args break at the spaces.

It would be great if Cirrus CLI can provide a way to configure the guest dir where the host dir is mounted inside the VM. This way, we can mount it somewhere else (say, `/Users/admin/project-dir` etc.)

**Comment by fkorotkov** [comment]
Can probably do something similar to https://github.com/cirruslabs/gitlab-tart-executor/pull/65

**Comment by ncs29** [comment]
Great, thanks @edigaryev for the super-quick resolution. Can you pls release a new version so that we can start using this! 👍

**Comment by edigaryev** [comment]
> Great, thanks @edigaryev for the super-quick resolution. Can you pls release a new version so that we can start using this! 👍

Just released the [`0.116.0`](https://github.com/cirruslabs/cirrus-cli/releases/tag/v0.116.0).
