### ISSUE TITLE
Volume preparation failure due to architecture mismatch

### ISSUE THREAD

**Issue by virtu** [cirruslabs/cirrus-cli#721]
Trying to run the example form the github page on an aarch64 Linux machine fails with the following errors:

```bash
% cirrus run
🕕 'Tests (Go 1.15)' Task 5s
   ❌ Preparing execution environment... 5.0s
      Preparing volume to work with...
      Failed to create a volume from working directory: working volume creation failed: helper container exited with  error and exit code 1

🕕 'Tests (Go 1.14)' Task 0s
   ❌ Preparing execution environment... 0.8s
      Preparing volume to work with...
      Failed to create a volume from working directory: working volume creation failed: helper container exited with  error and exit code 1
```

Inspecting the docker logs (`Apr 16 15:42:16 sphnix 2e0002828441[3042200]: exec /bin/sh: exec format error`) suggests the helper image used to prepare the volume to be the culprit:

```shell
% docker image list
REPOSITORY                           TAG        IMAGE ID       CREATED       SIZE
ghcr.io/cirruslabs/cirrus-ci-agent   v1.134.0   97ccf23d491f   2 weeks ago   36.1MB
% docker inspect 97ccf23d491f | grep Arch
        "Architecture": "amd64",
% uname -m
aarch64
```

I tried removing the image and manually adding and tagging the [arm64 image](https://github.com/cirruslabs/cirrus-ci-agent/pkgs/container/cirrus-ci-agent). Unfortunately, this didn't work. When I run cirrus, it will download and use the amd64 image.

Any workarounds?

**Comment by edigaryev** [comment]
>Any workarounds?

Please use an `arm_container` instance instead of the `container` instance, see https://github.com/cirruslabs/cirrus-cli/issues/621 and https://github.com/cirruslabs/cirrus-cli/pull/626.

**Comment by virtu** [comment]
#725 works as workaround.

The one downside is this implies is having a modified `.travis.yml` in the repo for `cirrus-cli`.
I'll fix that for now by using a wrapper script for cirrus that contains a simple `sed` statement. Thanks!
