### ISSUE TITLE
Failed to create a volume from working directory

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-cli#74]
```
> cirrus run -v rubocop
gRPC server is listening at http://172.17.0.1:36311
running task rubocop (3)
Started 'rubocop'
Started 'Preparing execution environment...'
Preparing volume to work with...
Failed to create a volume from working directory: working volume creation failed: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=gcr.io%2Fcirrus-ci-community%2Fcirrus-ci-agent&tag=v1.8.0": dial unix /var/run/docker.sock: connect: permission denied
'Preparing execution environment...' failed in 0.0s!
Error: working volume creation failed: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=gcr.io%2Fcirrus-ci-community%2Fcirrus-ci-agent&tag=v1.8.0": dial unix /var/run/docker.sock: connect: permission denied
2020/09/10 00:29:03 working volume creation failed: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=gcr.io%2Fcirrus-ci-community%2Fcirrus-ci-agent&tag=v1.8.0": dial unix /var/run/docker.sock: connect: permission denied
```

Repository: https://github.com/AlexWayfer/alexwayfer.name

Environment: ArchLinux. There is no `docker` permissions for regular user, we should use `sudo`. So, when and how I need to use `sudo` more correctly?

**Comment by fkorotkov** [comment]
If you need to use `sudo` to run Docker could you please try to run `sudo cirrus run -v rubocop`?

**Comment by AlexWayfer** [comment]
> If you need to use `sudo` to run Docker could you please try to run `sudo cirrus run -v rubocop`?

I think I can, but… is it secure?

**Comment by AlexWayfer** [comment]
BTW, it works.

So, or we can find out a more secure (and better) way to do `sudo` for `cirrus-cli`, either we should add this note somewhere to README or anything else (at least for Arch Linux users).

**Comment by edigaryev** [comment]
> There is no `docker` permissions for regular user, we should use `sudo`.

Have you considered creating a separate user added to the `docker` group and running CLI as this user?

This will solve the `sudo` problem in case adding your own user into the `docker` group is not an option.

**Comment by AlexWayfer** [comment]
I see this warning in Arch Linux Wiki:

> Anyone added to the docker group is root equivalent because they can use the docker run --privileged command to start containers with root privileges.

So, I don't want to have any additional user with root privileges, it's dangerous.

I think I understand the issue, it's more on Arch Linux and my side, but my suggestion was to add `sudo` to some parts inside of `cirrus-cli` with `docker`, maybe distro-depending. But as you wish, you can close this issue.

**Comment by edigaryev** [comment]
Closing since you can now use [rootless Podman](https://github.com/cirruslabs/cirrus-cli/blob/master/INSTALL.md#rootless-builds) to run builds as a regular user.
