### ISSUE TITLE
Cannot install Cirrus CLI on macOS

### ISSUE THREAD

**Issue by bartekpacia** [cirruslabs/cirrus-cli#742]
cc @fkorotkov 

```
bartek at Barteks-MacBook in ~
$ brew update
==> Updating Homebrew...
Already up-to-date.
bartek at Barteks-MacBook in ~
$ brew install cirruslabs/cli/cirrus
cirrus: Linux is required for this software.
Error: cirrus: An unsatisfied requirement failed this build.
```

I think it started occuring after latest Cirrus CLI update (0.122.0)

**Comment by fkorotkov** [comment]
Fixed in https://github.com/cirruslabs/homebrew-cli/commit/67d5b13cb41224bca4114cd049578c464a24b797

Sorry for the inconvenience. Having troubles notarizing binaries for macOS Sequoia.

**Comment by bartekpacia** [comment]
np 

Glad it was resolved quickly:)
