### ISSUE TITLE
[worker] `podman system service` process accumulation

### ISSUE THREAD

**Issue by duckinator** [cirruslabs/cirrus-cli#766]
When running `cirrus worker run` with the container isolation on Debian 12, with the Podman backend, each task spawns a `podman system service` process that never exits.

At one point, the system had accumulated 158 of these processes, but hadn't run any tasks for over 3 hours.

**WORKAROUND:** Periodically close and re-opening `cirrus worker run`.

**Comment by duckinator** [comment]
This line is what runs the process that doesn't exit:

https://github.com/cirruslabs/cirrus-cli/blob/95e9f68f96873e4d9f8d9bad2f6ce6208aef491d/internal/executor/instance/containerbackend/podman_linux.go#L43

However, my understanding is that this function should eventually be called to kill it:

https://github.com/cirruslabs/cirrus-cli/blob/95e9f68f96873e4d9f8d9bad2f6ce6208aef491d/internal/executor/instance/containerbackend/podman_linux.go#L92-L121

I'm unsure whether this function isn't being called, or if it's just not working for some reason.

**Comment by duckinator** [comment]
I changed `"-t", "0"` to `"-t", "1"` and it spawns zombie processes instead.

This confirms that, for whatever reason, the `podman system service` processes are not being waited on.

**Comment by edigaryev** [comment]
I've tried reproducing your issue on Cirrus CLI 0.122.0 and Podman 3.4.4 on a clean `ghcr.io/cirruslabs/ubuntu:latest` instance with the following configuration to no avail:

```yaml
container:
  image: debian:latest

task:
  script: uname -a
```

https://github.com/cirruslabs/cirrus-cli/pull/767 might help, though.

**Comment by edigaryev** [comment]
I'm running it via [Tart](https://github.com/cirruslabs/tart) on macOS, but that probably doesn't matter much for this reproduce attempt.

**Comment by edigaryev** [comment]
@duckinator how does your `.cirrus.yml` look like? Which Cirrus CLI and Podman versions do you run and on which Linux distribution?

We'll probably need to reproduce this somehow first in order to devise a fix (if it's needed at all).

Looking at the code it should cleanup an instance or throw an error:

https://github.com/cirruslabs/cirrus-cli/blob/2a07c0284c95b1eec626b7e8341fa96ed3585ebe/internal/executor/executor.go#L208-L217

**Comment by duckinator** [comment]
Versions and such:
* distro: Debian 12 (bookworm)
* cirrus: 0.122.0-95e9f68
* podman: 4.3.1

The config I'm using on the worker is:

```yaml
token: "[...]"

security:
  allowed-isolations:
    container: {}

resources:
  cpu: 2

log:
  level: debug
```

The `.cirrus.yml` that triggers the worker is: https://github.com/duckinator/bork/blob/184e2c646d521bdfe8adef40c94082787e090944/.cirrus.yml (note that `macOS_task`, `FreeBSD_task`, and `Windows_task` are currently marked as skipped).

**Comment by edigaryev** [comment]
Please check out the new [`0.122.1` release](https://github.com/cirruslabs/cirrus-cli/releases/tag/v0.122.1), it should the issue you're encountering 🙌

**Comment by duckinator** [comment]
Unfortunately with cirrus-cli 0.122.1-8ae0752, it's actually worse: the problem is still there, but now the podman process lingers _even after I stop `cirrus worker run`_. Previously, that was making it exit.

**Comment by edigaryev** [comment]
> Unfortunately with cirrus-cli 0.122.1-8ae0752, it's actually worse: the problem is still there, but now the podman processes linger _even after I stop `cirrus worker run`_. Previously, that was making it exit.

Indeed, I was testing the fix using `cirrus run`, yet, Persistent Worker has slightly different code path.

This will be fixed in https://github.com/cirruslabs/cirrus-cli/pull/769.

Sorry for the inconvenience!

**Comment by duckinator** [comment]
Confirmed that the latest 0.122.2-6faa293 works. Thank you for fixing this so quickly, it's very appreciated!
