### ISSUE TITLE
Allow OrbStack as container runtime?

### ISSUE THREAD

**Issue by bartekpacia** [cirruslabs/cirrus-cli#781]
It's this new cool shiny thing: https://orbstack.dev

**Comment by edigaryev** [comment]
The OrbStack is already supported, even if you [don't allow admin access](https://docs.orbstack.dev/faq#admin) on the first run.

Thanks to [Docker contexts](https://docs.docker.com/engine/manage-resources/contexts/), Cirrus CLI's Docker container backend automatically uses the current context, which in case of OrbStack will point to its Unix domain socket file.
