### ISSUE TITLE
Investigate memory usage of `cache` instructions.

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#799]
There are reports that a cache entry of `1003Mb` consumes more than `2GB` of memory which gets k8s pods to get `OOMKilled`.

**Comment by edigaryev** [comment]
Closing because of improbable reproducibility, please reopen if new details will arise.

Previous issues and PRs, for reference:

* https://github.com/cirruslabs/cirrus-ci-agent/issues/346
* https://github.com/cirruslabs/cirrus-ci-agent/pull/347
