### ISSUE TITLE
Option to run a task by id

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#9]
It will be nice to be able to run a task by id locally like `cirrus run -task-id 123`. We'll need to implement a separate RPC method to get a configuration and environment variables. Can be handy in addition to #8

**Comment by edigaryev** [comment]
As far as I remember we've decided to run tasks by names instead of IDs, and that was implemented in https://github.com/cirruslabs/cirrus-cli/pull/21.
