### ISSUE TITLE
Cirrus Template Testing

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-cli#95]
Since now you can create configurations in Starlark we need to think about how to test them.

A simple template repository looks like:

```
lib.star
```

One thing we can do it to have `tests` folder with test projects and check that evaluation the template yielded expected tasks.

```
tests/foo-project/.cirrus.env # optional file with environment variables for evaluation
tests/foo-project/.cirrus.star # will contain load("../../lib.star", "foo") and main for testing
tests/foo-project/.cirrus.expected.yml # expected result to diff agains
tests/foo-project/package.json # some other files for testing `fs` for example
lib.star
```

Then we can have a separate internal subcommand like `cirrus internal test tests/*` that will take a list of folders and run evaluation and checking against the expected YML.

**Comment by edigaryev** [comment]
What do you think about re-using [pytest](https://docs.pytest.org/en/stable/)'s conventions in regards to [naming](https://docs.pytest.org/en/reorganize-docs/new-docs/user/naming_conventions.html) and let the `test_*()` functions be automatically evaluated when running `cirrus validate --test`, which will also output the test report using [echelon](https://github.com/cirruslabs/echelon)?

An example of test for [Golang's template](https://github.com/cirrus-templates/golang/pull/1) would look like this (this will be added to `lib.star`):

```python
load("cirrus", "test", "env", "fs", "yaml")

def test_detect_tasks():
    # Creates a file layered on top of the real FS
    # The file will be gone once this function finishes
    test.mock_file(".golangci.yml", "")

    for task in detect_tasks():
        if task["Name"] == "Lint":
            return

    fail("golangci-lint wasn't detected")

def test_lint_task():
    # Changes the environment
    # The changes will be gone once this function finishes
    env["SOME_VARIABLE"] = "some value"

    expected = yaml.loads(fs.read("fixtures/only-lint.yml"))
    actual = [test_lint_task()]
    if expected != actual:
        fail("expected '%s', got '%s' instead" % (expected, actual))
```

`cirrus validate --test` will only evaluate `test_*()` functions in `.star`-files from the repository it's being run to avoid testing dependencies.

**Comment by fkorotkov** [comment]
This can also work. I think having it in a separate `test_lib.star` will be better since then we can add `test` as a global builtin for testing. Maybe also add `assert` for things like `assert.equal()` which will output a pretty diff if there are differences. What do you think?
